input {
  tcp {
    port => 5000
    codec => json_lines
  }

  beats {
    port => 5044
  }
}

filter {
  if ![event][dataset] {
    mutate {
      add_field => { "[event][dataset]" => "trading-engine" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "trading-engine-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
