namespace TradingEngine.Clients.PolyMarket.Models;

public record Market
{
    public string? Id { get; init; }
    public string? Question { get; init; }
    public string ConditionId { get; init; }
    public string Slug { get; init; }
    public string ResolutionSource { get; init; }
    public DateTime EndDate { get; init; }
    public string Liquidity { get; init; }
    public DateTime StartDate { get; init; }
    public string Image { get; init; }
    public string Icon { get; init; }
    public string Description { get; init; }
    public string Outcomes { get; init; }
    public string OutcomePrices { get; init; }
    public string Volume { get; init; }
    public bool Active { get; init; }
    public bool Closed { get; init; }
    public string MarketMakerAddress { get; init; }
    public DateTime CreatedAt { get; init; }
    public DateTime UpdatedAt { get; init; }
    public bool New { get; init; }
    public bool Featured { get; init; }
    public string SubmittedBy { get; init; }
    public bool Archived { get; init; }
    public string ResolvedBy { get; init; }
    public bool Restricted { get; init; }
    public string GroupItemTitle { get; init; }
    public string GroupItemThreshold { get; init; }
    public string QuestionID { get; init; }
    public bool EnableOrderBook { get; init; }
    public decimal OrderPriceMinTickSize { get; init; }
    public int OrderMinSize { get; init; }
    public decimal VolumeNum { get; init; }
    public decimal LiquidityNum { get; init; }
    public string EndDateIso { get; init; }
    public string StartDateIso { get; init; }
    public bool HasReviewedDates { get; init; }
    public decimal Volume24hr { get; init; }
    public decimal Volume1wk { get; init; }
    public decimal Volume1mo { get; init; }
    public decimal Volume1yr { get; init; }
    public string GameStartTime { get; init; }
    public int SecondsDelay { get; init; }
    public string ClobTokenIds { get; init; }
    public string UmaBond { get; init; }
    public string UmaReward { get; init; }
    public decimal Volume24hrClob { get; init; }
    public decimal Volume1wkClob { get; init; }
    public decimal Volume1moClob { get; init; }
    public decimal Volume1yrClob { get; init; }
    public decimal VolumeClob { get; init; }
    public decimal LiquidityClob { get; init; }
    public int CustomLiveness { get; init; }
    public bool AcceptingOrders { get; init; }
    public bool NegRisk { get; init; }
    public string NegRiskMarketID { get; init; }
    public string NegRiskRequestID { get; init; }
    public bool Ready { get; init; }
    public bool Funded { get; init; }
    public DateTime AcceptingOrdersTimestamp { get; init; }
    public bool Cyom { get; init; }
    public double Competitive { get; init; }
    public bool PagerDutyNotificationEnabled { get; init; }
    public bool Approved { get; init; }
    public double RewardsMinSize { get; init; }
    public double RewardsMaxSpread { get; init; }
    public decimal Spread { get; init; }
    public decimal OneDayPriceChange { get; init; }
    public decimal OneWeekPriceChange { get; init; }
    public decimal LastTradePrice { get; init; }
    public decimal BestBid { get; init; }
    public decimal BestAsk { get; init; }
    public bool AutomaticallyActive { get; init; }
    public bool ClearBookOnStart { get; init; }
    public bool ManualActivation { get; init; }
    public bool NegRiskOther { get; init; }
    public string SportsMarketType { get; init; }
    public string UmaResolutionStatuses { get; init; }
    public bool PendingDeployment { get; init; }
    public bool Deploying { get; init; }
    public DateTime DeployingTimestamp { get; init; }
    public bool RfqEnabled { get; init; }
    public bool HoldingRewardsEnabled { get; init; }
    public bool FeesEnabled { get; init; }
    public bool RequiresTranslation { get; init; }
    public string FeeType { get; init; }
}