namespace TradingEngine.Clients.PolyMarket.Models;

public class Market
{
    public string Id { get; set; }
    public string Question { get; set; }
    public string ConditionId { get; set; }
    public string Slug { get; set; }
    public string ResolutionSource { get; set; }
    public DateTime EndDate { get; set; }
    public string Liquidity { get; set; }
    public DateTime StartDate { get; set; }
    public string Image { get; set; }
    public string Icon { get; set; }
    public string Description { get; set; }
    public string Outcomes { get; set; }
    public string OutcomePrices { get; set; }
    public string Volume { get; set; }
    public bool Active { get; set; }
    public bool Closed { get; set; }
    public string MarketMakerAddress { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public bool New { get; set; }
    public bool Featured { get; set; }
    public string SubmittedBy { get; set; }
    public bool Archived { get; set; }
    public string ResolvedBy { get; set; }
    public bool Restricted { get; set; }
    public string GroupItemTitle { get; set; }
    public string GroupItemThreshold { get; set; }
    public string QuestionID { get; set; }
    public bool EnableOrderBook { get; set; }
    public decimal OrderPriceMinTickSize { get; set; }
    public int OrderMinSize { get; set; }
    public decimal VolumeNum { get; set; }
    public decimal LiquidityNum { get; set; }
    public string EndDateIso { get; set; }
    public string StartDateIso { get; set; }
    public bool HasReviewedDates { get; set; }
    public decimal Volume24hr { get; set; }
    public decimal Volume1wk { get; set; }
    public decimal Volume1mo { get; set; }
    public decimal Volume1yr { get; set; }
    public string GameStartTime { get; set; }
    public int SecondsDelay { get; set; }
    public string ClobTokenIds { get; set; }
    public string UmaBond { get; set; }
    public string UmaReward { get; set; }
    public decimal Volume24hrClob { get; set; }
    public decimal Volume1wkClob { get; set; }
    public decimal Volume1moClob { get; set; }
    public decimal Volume1yrClob { get; set; }
    public decimal VolumeClob { get; set; }
    public decimal LiquidityClob { get; set; }
    public int CustomLiveness { get; set; }
    public bool AcceptingOrders { get; set; }
    public bool NegRisk { get; set; }
    public string NegRiskMarketID { get; set; }
    public string NegRiskRequestID { get; set; }
    public bool Ready { get; set; }
    public bool Funded { get; set; }
    public DateTime AcceptingOrdersTimestamp { get; set; }
    public bool Cyom { get; set; }
    public double Competitive { get; set; }
    public bool PagerDutyNotificationEnabled { get; set; }
    public bool Approved { get; set; }
    public int RewardsMinSize { get; set; }
    public int RewardsMaxSpread { get; set; }
    public decimal Spread { get; set; }
    public decimal OneDayPriceChange { get; set; }
    public decimal OneWeekPriceChange { get; set; }
    public decimal LastTradePrice { get; set; }
    public decimal BestBid { get; set; }
    public decimal BestAsk { get; set; }
    public bool AutomaticallyActive { get; set; }
    public bool ClearBookOnStart { get; set; }
    public bool ManualActivation { get; set; }
    public bool NegRiskOther { get; set; }
    public string SportsMarketType { get; set; }
    public string UmaResolutionStatuses { get; set; }
    public bool PendingDeployment { get; set; }
    public bool Deploying { get; set; }
    public DateTime DeployingTimestamp { get; set; }
    public bool RfqEnabled { get; set; }
    public bool HoldingRewardsEnabled { get; set; }
    public bool FeesEnabled { get; set; }
    public bool RequiresTranslation { get; set; }
    public string FeeType { get; set; }
}